apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ffez8fc66-python
  janus-idp.io/tekton: ffez8fc66-python
  backstage.io/kubernetes-id: ffez8fc66-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ffez8fc66-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
